server:
  port: ${server.port}

spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka.client.service-url.defaultZone}
  instance:
    hostname: ${hostname:192.168.2.179}
